### ISSUE TITLE
JSP

### ISSUE THREAD

**Issue by MarckDJ** [DeepTure/WebList#2]

**Comment by MarckDJ** [comment]
cambien los html por jsp's

**Comment by cdelaof26** [comment]
Hace falta crear un proyecto en netbeans ?

**Comment by MarckDJ** [comment]
no lo creo, solo hay que hacer que se ejecute en un jsp. como en el php para heroku

**Comment by Jafet5757** [comment]
para que?, no es necesario cambiar los html

**Comment by MarckDJ** [comment]
por eso digo solo agregar el jsp

**Comment by MarckDJ** [comment]
es NECESARIO cambiar los html por los jsp para crear las conecciones a db

**Comment by cdelaof26** [comment]
Todos los archivos y referencias fueron cambiadas de .html a JSP
