### ISSUE TITLE
Resp no funciona

### ISSUE THREAD

**Issue by MarckDJ** [DeepTure/WebList#4]
al acercar la pagina de 175% a 200% el resp.css se buguea todo

**Comment by cdelaof26** [comment]
Como primer punto: Si funciona, el que no funcione en ciertas circunstancias no quiere decir que no funcione para nada.

Segundo: No se "buggea todo", por ahora el CSS responsivo esta en desarrollo y aun no tiene soporte para esas pantallas.

Tercero: El problema es que el nav / div principal no son del tamaño adecuado y el borde es tan pequeño que no aparece en 175 y 200%.

Si tienes problema con tu pantalla dale soporte al CSS modificandolo.
